default: &default
  app_url: "http://localhost:3000"
  static_pages:
    home: "http://localhost:3000"
    help: "http://localhost:3000/help"
    contact: "http://localhost:3000/contact"
    about: "http://localhost:3000/about"
    signup: "http://localhost:3000/signup"
  outsideLink:
    railsTutorial: "https://www.railstutorial.org"
    railsTutorialHelp: "https://www.railstutorial.org/help"
    railsTutorialBook: "https://www.railstutorial.org/book"
    railsTutorialContact: "https://www.railstutorial.org/contact"
    michaelHartl: "https://www.michaelhartl.com"
    learnEnough: "https://www.learnenough.com"
    railsNews: "https://news.railstutorial.org"
    rubyOnRails: "https://rubyonrails.org"
    screencastsTutorial: "https://screencasts.railstutorial.org"
  validate:
    email:
      format: "\\A[\\w+\\-.]+@[a-z\\d\\-.]+\\.[a-z]+\\z"
      maxLength: 255
    name:
      maxLength: 50
    password:
      minLength: 6
  users_pagination:
      per_page: 10
  avatar:
    size: 80
development:
  <<: *default
